

package app.cash.burst.kotlin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link app.cash.burst.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("burst-kotlin-plugin-tests/src/test/data/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  private void run(String fileName) {
    runTest("burst-kotlin-plugin-tests/src/test/data/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("burst-kotlin-plugin-tests/src/test/data/box/arguments")
  @TestDataPath("$PROJECT_ROOT")
  public class Arguments {
    private void run(String fileName) {
      runTest("burst-kotlin-plugin-tests/src/test/data/box/arguments/" + fileName);
    }

    @Test
    public void testAllFilesPresentInArguments() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/box/arguments"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("BooleanDefaultValues.kt")
    public void testBooleanDefaultValues() {
      run("BooleanDefaultValues.kt");
    }

    @Test
    @TestMetadata("BooleanParameters.kt")
    public void testBooleanParameters() {
      run("BooleanParameters.kt");
    }

    @Test
    @TestMetadata("BurstValues.kt")
    public void testBurstValues() {
      run("BurstValues.kt");
    }

    @Test
    @TestMetadata("BurstValuesHasReasonableSymbolName.kt")
    public void testBurstValuesHasReasonableSymbolName() {
      run("BurstValuesHasReasonableSymbolName.kt");
    }

    @Test
    @TestMetadata("BurstValuesJustOne.kt")
    public void testBurstValuesJustOne() {
      run("BurstValuesJustOne.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithEnumValues.kt")
    public void testBurstValuesWithEnumValues() {
      run("BurstValuesWithEnumValues.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithInlineClassDeclarations.kt")
    public void testBurstValuesWithInlineClassDeclarations() {
      run("BurstValuesWithInlineClassDeclarations.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithInlineFunctions.kt")
    public void testBurstValuesWithInlineFunctions() {
      run("BurstValuesWithInlineFunctions.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithNameCollisions.kt")
    public void testBurstValuesWithNameCollisions() {
      run("BurstValuesWithNameCollisions.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithObjectValues.kt")
    public void testBurstValuesWithObjectValues() {
      run("BurstValuesWithObjectValues.kt");
    }

    @Test
    @TestMetadata("BurstValuesWithOverlyLongNames.kt")
    public void testBurstValuesWithOverlyLongNames() {
      run("BurstValuesWithOverlyLongNames.kt");
    }

    @Test
    @TestMetadata("ConstructorParameters.kt")
    public void testConstructorParameters() {
      run("ConstructorParameters.kt");
    }

    @Test
    @TestMetadata("DefaultArgumentsHonored.kt")
    public void testDefaultArgumentsHonored() {
      run("DefaultArgumentsHonored.kt");
    }

    @Test
    @TestMetadata("FunctionParameters.kt")
    public void testFunctionParameters() {
      run("FunctionParameters.kt");
    }

    @Test
    @TestMetadata("NullableBooleanAsDefault.kt")
    public void testNullableBooleanAsDefault() {
      run("NullableBooleanAsDefault.kt");
    }

    @Test
    @TestMetadata("NullableBooleanNoDefault.kt")
    public void testNullableBooleanNoDefault() {
      run("NullableBooleanNoDefault.kt");
    }

    @Test
    @TestMetadata("NullableBurstValuesAsDefault.kt")
    public void testNullableBurstValuesAsDefault() {
      run("NullableBurstValuesAsDefault.kt");
    }

    @Test
    @TestMetadata("NullableBurstValuesNoDefault.kt")
    public void testNullableBurstValuesNoDefault() {
      run("NullableBurstValuesNoDefault.kt");
    }

    @Test
    @TestMetadata("NullableEnumAsDefault.kt")
    public void testNullableEnumAsDefault() {
      run("NullableEnumAsDefault.kt");
    }

    @Test
    @TestMetadata("NullableEnumNoDefault.kt")
    public void testNullableEnumNoDefault() {
      run("NullableEnumNoDefault.kt");
    }
  }

  @Nested
  @TestMetadata("burst-kotlin-plugin-tests/src/test/data/box/coroutines")
  @TestDataPath("$PROJECT_ROOT")
  public class Coroutines {
    private void run(String fileName) {
      runTest("burst-kotlin-plugin-tests/src/test/data/box/coroutines/" + fileName);
    }

    @Test
    public void testAllFilesPresentInCoroutines() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/box/coroutines"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("Coroutines.kt")
    public void testCoroutines() {
      run("Coroutines.kt");
    }

    @Test
    @TestMetadata("CoroutinesAndTestComposition.kt")
    public void testCoroutinesAndTestComposition() {
      run("CoroutinesAndTestComposition.kt");
    }
  }
}
