

package app.cash.burst.kotlin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link app.cash.burst.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("burst-kotlin-plugin-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("UnexpectedClassArgumentType.kt")
  public void testUnexpectedClassArgumentType() {
    runTest("burst-kotlin-plugin-tests/src/test/data/diagnostic/UnexpectedClassArgumentType.kt");
  }

  @Test
  @TestMetadata("UnexpectedFunctionArgumentType.kt")
  public void testUnexpectedFunctionArgumentType() {
    runTest("burst-kotlin-plugin-tests/src/test/data/diagnostic/UnexpectedFunctionArgumentType.kt");
  }
}
