

package app.cash.burst.kotlin;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link app.cash.burst.kotlin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("burst-kotlin-plugin-tests/src/test/data/dump")
@TestDataPath("$PROJECT_ROOT")
public class IrDumpTestGenerated extends AbstractIrDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("burst-kotlin-plugin-tests/src/test/data/dump/ir")
  @TestDataPath("$PROJECT_ROOT")
  public class Ir {
    @Test
    public void testAllFilesPresentInIr() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("burst-kotlin-plugin-tests/src/test/data/dump/ir"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("ConstructorParameters.kt")
    public void testConstructorParameters() {
      runTest("burst-kotlin-plugin-tests/src/test/data/dump/ir/ConstructorParameters.kt");
    }

    @Test
    @TestMetadata("FunctionParameters.kt")
    public void testFunctionParameters() {
      runTest("burst-kotlin-plugin-tests/src/test/data/dump/ir/FunctionParameters.kt");
    }
  }
}
